matrix:
    fast_finish: true
    allow_failures:
        -
            env: JOB=APK
        -
            env: JOB=IPA
    include:
        -
            env: JOB=TEST
            language: dart
            dist: xenial
            addons: {apt: {packages: [lib32stdc++6]}}
            install: ['git clone https://github.com/flutter/flutter.git -b stable', './flutter/bin/flutter doctor', 'gem install coveralls-lcov']
            script: ['./flutter/bin/flutter packages pub get --packages-dir', './flutter/bin/flutter test --coverage']
            after_success: ['coveralls-lcov coverage/lcov.info']
        -
            env: JOB=APK
            os: linux
            language: android
            licenses: [android-sdk-preview-license-.+, android-sdk-license-.+, google-gdk-license-.+]
            android: {components: [tools, platform-tools, build-tools-25.0.3, android-25, sys-img-armeabi-v7a-google_apis-25, extra-android-m2repository, extra-google-m2repository, extra-google-android-support]}
            jdk: oraclejdk8
            sudo: false
            addons: {apt: {sources: [ubuntu-toolchain-r-test], packages: [libstdc++6, fonts-droid]}}
            before_script: ['wget https://services.gradle.org/distributions/gradle-3.5-bin.zip', 'unzip -qq gradle-3.5-bin.zip', 'export GRADLE_HOME=$PWD/gradle-3.5', 'export PATH=$GRADLE_HOME/bin:$PATH', 'git clone https://github.com/flutter/flutter.git -b stable', 'wget https://github.com/AdityaMulgundkar/flutter_opencv/releases/download/sdk-license/sdk-license.zip', 'unzip -qq sdk-license.zip', 'mkdir $ANDROID_HOME/licenses || true', 'cp ./licenses/* $ANDROID_HOME/licenses/']
            script: ['cd example', '../flutter/bin/flutter -v build apk']
    cache:
        directories:
            - $HOME/.pub-cache
