matrix:
    include:
        -
            env: JOB=TEST
            language: dart
            dist: xenial
            addons: {apt: {packages: [lib32stdc++6]}}
            install: ['git clone https://github.com/flutter/flutter.git -b stable', './flutter/bin/flutter doctor', 'gem install coveralls-lcov']
            script: ['./flutter/bin/flutter packages pub get --packages-dir', './flutter/bin/flutter test --coverage']
            after_success: ['coveralls-lcov coverage/lcov.info']
            cache: {directories: [$HOME/.pub-cache]}
        -
            env: JOB=DOCS
            language: ruby
            rvm: [2.4.1]
            before_install: ['chmod +x setup', 'chmod +x deploy', 'chmod +x automated']
            install: [./docs/bin/setup]
            script: ['cd docs', 'bundle exec jekyll build --trace', 'bundle exec htmlproofer ./_site --only-4xx --allow-hash-href']
            after_success: ['test $TRAVIS_PULL_REQUEST == "false" && test $TRAVIS_BRANCH == "master" && "./bin/automated"']
            global: [NOKOGIRI_USE_SYSTEM_LIBRARIES=true, {USERNAME: AdityaMulgundkar}, {EMAIL: "adityamulgundkar.nmims\nsecure: hegOvpwoOxE5k1sz992DNGRkQZsIErjKOuClj+qoHBIW92T3U4i0bMrH7++P7Rl/yxx+4WZtctwoDiTPbG/Q33TVSahMqdyttMMLJRse8zD2Xp+uLzY9q8axCNYbcFLOwIakkKo/p/RI55Rd00zDEphbAthqQjdj3xJI7ODPEoDx3Ou7bR4XMhGt16ESeDlHt9aqZvCMGUp4qEgLyxqpIEGPbKrnz9jF3gtb+RXOR5AC/68V+J0eIUWIsOaWCFE5nk1ykokiutJm0VjDBNyuZU0QmimTA2OXQOZGJYGnoWfokWWN1yCvWefl3pDNNAqhuuw4mQ6s90erAStGJ76OMNllg5uaAbqBdYbok2u0R0mDa66UtnXxyuW6z/7/NHzLt7DY3eGOAiaudji/QVHIVz4Dh/cpTS+ClG0FXMZHFUBDv7UPnSnHbdwVguNplHJ1jX8gkYAljqg+XGlMDy/TJ2t833imp7V03iV6eH5euBv+umS+ELFluywXawFME8CrCXL17W/7nDydYv1MyHrCHD2mIt4Uwtd46mWvMn/LGk7XQmdyi16PEOvyOpKS5RhyKjEgt1JiYK8RVEy+j77c1SwtepC5aYGI1yd4mUmEaavoO46TqJhqB/shTEEZiykH3ToARYn4RnqAuzQKrD5nQ/a+ld6vl/cNbMHTm7oXWDg="}]
