name: opencv
description: A new Flutter plugin.
version: 1.0.0
homepage: https://github.com/AdityaMulgundkar/flutter_opencv

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  plugin:
    androidPackage: com.mulgundkar.opencv
    pluginClass: OpenCV4Plugin
